hosts:
# Bastions
  - name: Review-Bastion
    address: 54.245.154.52:22
    username: ec2-user
    identity: /Users/jason.figge/.ssh/pingidp2.pem
    known_hosts: /Users/jason.figge/.ssh/known_hosts
  - name: Staging-Bastion
    address: 35.164.43.75:22
    username: ec2-user
    identity: /Users/jason.figge/.ssh/pingidp2.pem
    known_hosts: /Users/jason.figge/.ssh/known_hosts
  - name: Staging-Fedramp-Bastion
    address: 35.89.225.131:22
    username: ec2-user
    identity: /Users/jason.figge/.ssh/stagingfed.pem
    known_hosts: /Users/jason.figge/.ssh/known_hosts
# Jumped hosts
  - name: Review Ping A
    address: 172.21.194.80:22
    username: ec2-user
    identity: /Users/jason.figge/.ssh/pingidp2.pem
    jump_host: Review-Bastion
  - name: Staging-Federate
    address: 172.21.194.171:22
    username: ec2-user
    identity: /Users/jason.figge/.ssh/stagingfed.pem
    jump_host: Staging-Fedramp-Bastion
tunnels:
# Review
  - name: Review API Gateway
    local: 0.0.0.0:8000
    host: Review-Bastion
    forward: ccp-internal.gateway.review.innovationlabs.teradata.com:443
  - name: Review Postgres
    local: 0.0.0.0:8432
    host: Review-Bastion
    forward: postgres.review.innovationlabs.teradata.com:5432
  - name: Review Ping Federate UI
    local: 0.0.0.0:8999
    host: Review-Bastion
    forward: 172.21.194.80:9999
  - name: Review Ping Federate OAuth
    local: 0.0.0.0:8031
    host: Review-Bastion
    forward: 172.21.194.80:9031
  - name: Vault Review
    local: 0.0.0.0:8208
    host: Review-Bastion
    forward: vault.internal.teracloud.teradata.com:8200
  # Staging
  - name: Staging API Gateway
    local: 0.0.0.0:7000
    host: Staging-Bastion
    forward: ccp-internal.gateway.staging.innovationlabs.teradata.com:443
  - name: Staging Postgres
    local: 0.0.0.0:7432
    host: Staging-Bastion
    forward: postgres.staging.innovationlabs.teradata.com:5432
  - name: Staging Ping Federate UI
    local: 0.0.0.0:7999
    host: Staging-Bastion
    forward: 172.21.194.7:9999
  - name: Staging Ping Federate OAuth
    local: 0.0.0.0:7031
    host: Staging-Bastion
    forward: 172.21.194.7:9031
  - name: Vault Staging
    local: 0.0.0.0:8207
    host: Staging-Bastion
    forward: vault.internal.teracloud.teradata.com:8200
  # Staging Fedramp
  - name: Staging Fedramp API Gateway
    local: 0.0.0.0:5000
    host: Staging-Federate
    forward: ccp-internal.gateway.staging.fed.innovationlabs.teradata.com:443
  - name: Staging-Fedramp Postgres
    local: 0.0.0.0:4432
    host: Staging-Federate
    forward: postgres.staging.fed.innovationlabs.teradata.com:5432
  - name: Staging Fedramp Ping Federate UI
    local: 0.0.0.0:5999
    host: Staging-Federate
    forward: 172.21.194.171:9999
  - name: Staging Fedramp Ping Federate OAuth
    local: 0.0.0.0:5031
    host: Staging-Federate
    forward: 172.21.194.171:9031
  - name: Vault Staging Fedramp
    local: 0.0.0.0:8205
    host: Staging-Fedramp-Bastion
    forward: vault.internal.teracloud.teradata.com:8200
# LDAP non-prod
  - name: Non-Prod LDAP Could AD
    local: 0.0.0.0:636
    host: Review Ping A
    forward: ldaps.qateradatacloud.com:636
  - name: Non-Prod LDAP CS&S
    local: 0.0.0.0:1636
    host: Review Ping A
    forward: ldaps.qacustomer.teradata.com:636
